### PR TITLE
Support Node 0.10.x

### PR DESCRIPTION
**Pull request by parisholley**
Code doesn't need to check for read/write access, the later functions can throw if there are access problems. Instead just check for existence and keep current logic.

### CODE REVIEW

**Comment by mimmi20** [comment]
This cache class shall not raise any error or exception if a cache file does not exist or rights are missing. For this the checks are nessesary.

**Comment by mimmi20** [comment]
Please make sure that the `test for existence` does not raise errors. Please also fix the coding style and the existsting test. To re-add support for node.js 0.10, you have to change the package.json and the travis.yml

**Comment by parisholley** [comment]
@mimmi20 fixed the get item code. set item that was there before my changes didn't make sense as the return value is undefined on success of write sync, so returning the cache object is not useful. also, the writeSync method could throw an exception and isn't wrapped.

**Comment by parisholley** [comment]
@mimmi20 can you increment version and publish? thanks!

**Comment by mimmi20** [comment]
Its published now

**Pull request merged**
